export enum Category {
  BEBIDAS = 'BEBIDAS',
  MERCEARIA = 'MERCEARIA',
  LIMPEZA = 'LIMPEZA',
  HIGIENE_PERFUMARIA = 'HIGIENE_PERFUMARIA',
  PADARIA_MATINAIS = 'PADARIA_MATINAIS',
  PAPELARIA = 'PAPELARIA',
  PET_SHOP = 'PET_SHOP',
  AUTOMOTIVO = 'AUTOMOTIVO',
  FRIOS_CONGELADOS = 'FRIOS_CONGELADOS',
  ELETRONICOS_ELETROPORTATEIS = 'ELETRONICOS_ELETROPORTATEIS',
  HORTIFRUTI = 'HORTIFRUTI',
  CARNES_AVES_PEIXES = 'CARNES_AVES_PEIXES',
  VESTUARIO = 'VESTUARIO',
  UTILIDADES_DOMESTICAS = 'UTILIDADES_DOMESTICAS',
  JARDINAGEM = 'JARDINAGEM',
  DESCARTAVEIS_EMBALAGENS = 'DESCARTAVEIS_EMBALAGENS',
  ESPORTE_LAZER = 'ESPORTE_LAZER',
  OUTROS = 'OUTROS',
}

export const CategoryLabels: Record<Category, string> = {
  [Category.BEBIDAS]: 'Bebidas',
  [Category.MERCEARIA]: 'Mercearia',
  [Category.LIMPEZA]: 'Limpeza',
  [Category.HIGIENE_PERFUMARIA]: 'Higiene e Perfumaria',
  [Category.PADARIA_MATINAIS]: 'Padaria e Matinais',
  [Category.PAPELARIA]: 'Papelaria',
  [Category.PET_SHOP]: 'Pet Shop',
  [Category.AUTOMOTIVO]: 'Automotivo',
  [Category.FRIOS_CONGELADOS]: 'Frios e Congelados',
  [Category.ELETRONICOS_ELETROPORTATEIS]: 'Eletrônicos e Eletroportáteis',
  [Category.HORTIFRUTI]: 'Hortifrúti',
  [Category.CARNES_AVES_PEIXES]: 'Carnes, Aves e Peixes',
  [Category.VESTUARIO]: 'Vestuário',
  [Category.UTILIDADES_DOMESTICAS]: 'Utilidades Domésticas',
  [Category.JARDINAGEM]: 'Jardinagem',
  [Category.DESCARTAVEIS_EMBALAGENS]: 'Descartáveis e Embalagens',
  [Category.ESPORTE_LAZER]: 'Esporte e Lazer',
  [Category.OUTROS]: 'Outros',
};

export const CategoryDescriptions: Record<Category, string> = {
  [Category.BEBIDAS]: 'Águas, refrigerantes, sucos, cervejas, vinhos e demais bebidas',
  [Category.MERCEARIA]: 'Alimentos secos, enlatados, temperos, molhos e produtos básicos',
  [Category.LIMPEZA]: 'Produtos de limpeza doméstica, detergentes e desinfetantes',
  [Category.HIGIENE_PERFUMARIA]: 'Produtos de higiene pessoal, cosméticos e perfumes',
  [Category.PADARIA_MATINAIS]: 'Pães, biscoitos, cereais, achocolatados e produtos matinais',
  [Category.PAPELARIA]: 'Materiais de escritório, papéis, canetas e artigos escolares',
  [Category.PET_SHOP]: 'Ração, petiscos, brinquedos e acessórios para animais',
  [Category.AUTOMOTIVO]: 'Óleos, aditivos, acessórios e produtos para veículos',
  [Category.FRIOS_CONGELADOS]: 'Laticínios, embutidos, iogurtes e produtos congelados',
  [Category.ELETRONICOS_ELETROPORTATEIS]: 'Eletrônicos, pilhas, carregadores e eletroportáteis',
  [Category.HORTIFRUTI]: 'Frutas, verduras, legumes e produtos frescos',
  [Category.CARNES_AVES_PEIXES]: 'Carnes bovinas, suínas, aves, peixes e frutos do mar',
  [Category.VESTUARIO]: 'Roupas, calçados e acessórios de moda',
  [Category.UTILIDADES_DOMESTICAS]: 'Utensílios de cozinha, organização e decoração',
  [Category.JARDINAGEM]: 'Plantas, sementes, fertilizantes e ferramentas de jardim',
  [Category.DESCARTAVEIS_EMBALAGENS]: 'Pratos, copos, sacolas e embalagens descartáveis',
  [Category.ESPORTE_LAZER]: 'Equipamentos esportivos, brinquedos e artigos de lazer',
  [Category.OUTROS]: 'Produtos que não se enquadram nas categorias específicas',
};